### ISSUE TITLE
Testing Note Operations

### ISSUE THREAD

**Issue by sagedemage** [sagedemage/Notebook#35]
**Describe the feature request**
Write unit tests for note operations for the back-end.  

## Tasks
- [x] Add note test - **CREATE**
- **READ**:
  - [x] Fetch note test
  - [x] View notes test
- [x] Edit note test - **UPDATE**
- [x] Delete note test - **DELETE**

**Comment by sagedemage** [comment]
```
git fetch origin
git checkout 35-testing-note-operations-feature
```
