### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by sagedemage** [sagedemage/Notebook#5]
**Describe the feature request**
Implement registration page that registers a new user.

### Success
1. registers the account
2. gets redirected to the login page

### Failure
1. tries to register for an account
2. Gets an message box error

## Tasks
- [x] Write Registation html page
- [x] Write the code with axios to execute registering a new user
- [x] Throws an error if the user fails to register for the user

## Registration Validation
- [x] Password must be 8 characters or more
- [x] Passwords do not match
- [x] Email already exists
- [x] Username already exists
